#!/usr/bin/env python




##################################################
## DEPENDENCIES
import sys
import os
import os.path
try:
    import builtins as builtin
except ImportError:
    import __builtin__ as builtin
from os.path import getmtime, exists
import time
import types
from Cheetah.Version import MinCompatibleVersion as RequiredCheetahVersion
from Cheetah.Version import MinCompatibleVersionTuple as RequiredCheetahVersionTuple
from Cheetah.Template import Template
from Cheetah.DummyTransaction import *
from Cheetah.NameMapper import NotFound, valueForName, valueFromSearchList, valueFromFrameOrSearchList
from Cheetah.CacheRegion import CacheRegion
import Cheetah.Filters as Filters
import Cheetah.ErrorCatchers as ErrorCatchers
from Cheetah.compat import unicode

##################################################
## MODULE CONSTANTS
VFFSL=valueFromFrameOrSearchList
VFSL=valueFromSearchList
VFN=valueForName
currentTime=time.time
__CHEETAH_version__ = '3.1.0'
__CHEETAH_versionTuple__ = (3, 1, 0, 'final', 1)
__CHEETAH_genTime__ = 1538168597.857081
__CHEETAH_genTimestamp__ = 'Fri Sep 28 18:03:17 2018'
__CHEETAH_src__ = 'base.tmpl'
__CHEETAH_srcLastModified__ = 'Fri Sep 28 17:57:15 2018'
__CHEETAH_docstring__ = 'Autogenerated by Cheetah: The Python-Powered Template Engine'

if __CHEETAH_versionTuple__ < RequiredCheetahVersionTuple:
    raise AssertionError(
      'This template was compiled with Cheetah version'
      ' %s. Templates compiled before version %s must be recompiled.'%(
         __CHEETAH_version__, RequiredCheetahVersion))

##################################################
## CLASSES

class base(Template):

    ##################################################
    ## CHEETAH GENERATED METHODS


    def __init__(self, *args, **KWs):

        super(base, self).__init__(*args, **KWs)
        if not self._CHEETAH__instanceInitialized:
            cheetahKWArgs = {}
            allowedKWs = 'searchList namespaces filter filtersLib errorCatcher'.split()
            for k,v in KWs.items():
                if k in allowedKWs: cheetahKWArgs[k] = v
            self._initCheetahInstance(**cheetahKWArgs)
        

    def respond(self, trans=None):



        ## CHEETAH: main method generated for this template
        if (not trans and not self._CHEETAH__isBuffering and not callable(self.transaction)):
            trans = self.transaction # is None unless self.awake() was called
        if not trans:
            trans = DummyTransaction()
            _dummyTrans = True
        else: _dummyTrans = False
        write = trans.response().write
        SL = self._CHEETAH__searchList
        _filter = self._CHEETAH__currentFilter
        
        ########################################
        ## START - generated method body
        
        write('''<?xml version="1.0" encoding="UTF-8"?>
<routes>
  <vTypeDistribution id="typeVehicleDistribution">
        <!--http://www.toyota.com.au/prius-v/specifications/prius-v-->
        <vType id="Car" departSpeed="max" accel="3" decel="4.5" length="4.645" width="1.775" height="1.59" maxSpeed="17.88" speedDev="0.1" sigma="0.2" minGap="0.3" probability="0.2"/>
        <!--http://www.rms.nsw.gov.au/business-industry/heavy-vehicles/road-access/general-access-vehicles.html-->
        <vType id="Truck" accel="2.0" decel="4" length="12.5" width="2.5" height="4.3" maxSpeed="17.88" speedDev="0.1" sigma="0.2" minGap="0.3" probability="0.5"/>
        <!--http://www.modenabus.com/286/119/products/school_bus_school_bus_iveco_9_metres.html-->
        <vType id="Bus" accel="2.0" decel="4" length="9" width="2.4" height="3.2" maxSpeed="17.88" speedDev="0.1" sigma="0.2" minGap="0.3" probability="0.2"/>
  </vTypeDistribution>

  ''')
        _v = VFFSL(SL,"XMLZAO_DA_PORRA",True) # '$XMLZAO_DA_PORRA' on line 12, col 3
        if _v is not None: write(_filter(_v, rawExpr='$XMLZAO_DA_PORRA')) # from line 12, col 3.
        write('''

</routes>
''')
        
        ########################################
        ## END - generated method body
        
        return _dummyTrans and trans.response().getvalue() or ""
        
    ##################################################
    ## CHEETAH GENERATED ATTRIBUTES


    _CHEETAH__instanceInitialized = False

    _CHEETAH_version = __CHEETAH_version__

    _CHEETAH_versionTuple = __CHEETAH_versionTuple__

    _CHEETAH_genTime = __CHEETAH_genTime__

    _CHEETAH_genTimestamp = __CHEETAH_genTimestamp__

    _CHEETAH_src = __CHEETAH_src__

    _CHEETAH_srcLastModified = __CHEETAH_srcLastModified__

    _mainCheetahMethod_for_base = 'respond'

## END CLASS DEFINITION

if not hasattr(base, '_initCheetahAttributes'):
    templateAPIClass = getattr(base,
                               '_CHEETAH_templateClass',
                               Template)
    templateAPIClass._addCheetahPlumbingCodeToClass(base)


# CHEETAH was developed by Tavis Rudd and Mike Orr
# with code, advice and input from many other volunteers.
# For more information visit http://cheetahtemplate.org/

##################################################
## if run from command line:
if __name__ == '__main__':
    from Cheetah.TemplateCmdLineIface import CmdLineIface
    CmdLineIface(templateObj=base()).run()


